@root = http://127.0.0.1:9001
@api = {{root}}/api/v1

### Create user:
POST {{api}}/users

{
    "username":"user123",
    "email":"abceesasdfs@gmail.com",
    "password":"omegalul",
    "roles":[
        "admin"
    ]
}

### Get User with ID:
GET {{api}}/users
Cookie: {{auth.response.headers.Set-Cookie}} 


### Login user:
# @name auth
POST {{api}}/users/auth

{
    "username":"user123",
    "password":"omegalul"
}



### Create advisor:

POST {{api}}/advisors
Cookie: {{auth.response.headers.Set-Cookie}} 

{
    "first_name":"mamood",
    "last_name":"bozorge",
    "description":"failing advisor"
}

### Get advisors with pagination:

GET {{api}}/advisors
                    ?limit=10
                    &offset=0


### Create appointment:

POST {{api}}/appointments
Cookie: {{auth.response.headers.Set-Cookie}}

{
    "advisor_id":2,
    "start_datetime":"2020-02-16T18:49:53.148Z",
    "end_datetime":"2020-02-16T19:49:53.148Z"
}

### Add schedule for advisors:

POST {{api}}/advisors/schedule
Cookie: {{auth.response.headers.Set-Cookie}}

{
    "periods":
        [
            {
                "day_of_week":4,
                "start_time":"2020-02-12T12:04:47+03:30",
                "end_time":"2020-02-12T12:34:47+03:30"
            },
            {
                "day_of_week":6,
                "start_time":"2020-02-14T12:04:47+03:30",
                "end_time":"2020-02-14T12:34:47+03:30"
            }
        ]
}

### Get appointments for user:

GET {{api}}/appointments/user
Cookie: {{auth.response.headers.Set-Cookie}}


### Get appointments for advisor:

GET {{api}}/appointments/advisor
Cookie: {{auth.response.headers.Set-Cookie}}