@root = http://127.0.0.1:5555
@api = {{root}}/api/v1

POST {{api}}/users

{
    "username":"armin",
    "email":"abced@gmail.com",
    "password":"omegalul"
}

###

# @name auth
POST {{api}}/users/auth

{
    "username":"armin",
    "password":"omegalul"
}

###

POST {{api}}/advisors
Cookie: {{auth.response.headers.Set-Cookie}} 

{
    "first_name":"mamood",
    "last_name":"bozorge",
    "description":"failing advisor"
}

###

GET {{api}}/advisors
                    ?limit=10
                    &offset=0


###

POST {{api}}/appointments
Cookie: {{auth.response.headers.Set-Cookie}}

{
    "advisor_id":4,
    "start_datetime":"2020-02-15T18:49:53.148Z",
    "end_datetime":"2020-02-15T19:49:53.148Z"
}