@root = http://127.0.0.1:5555
@api = {{root}}/api/v1

POST {{api}}/users

{
    "username":"armin",
    "email":"abced@gmail.com",
    "password":"omegalul"
}

###

POST {{api}}/users/auth

{
    "username":"armin",
    "password":"omegalul"
}
